const TEAMS_BY_LEAGUE={"jpl":["RSC Anderlecht","Royal Antwerp FC","Cercle Brugge","Sporting Charleroi","Club Brugge","KAA Gent","KRC Genk","KV Kortrijk","KV Mechelen","RAAL La Louvière","Lommel SK","OH Leuven","STVV","SK Beveren","Standard de Liège","Royale Union Saint-Gilloise","KVC Westerlo","SV Zulte Waregem"],"epl":["AFC Bournemouth","Arsenal","Aston Villa","Brentford","Brighton & Hove Albion","Chelsea","Coventry City","Crystal Palace","Everton","Fulham","Hull City","Ipswich Town","Leeds United","Liverpool","Manchester City","Manchester United","Newcastle United","Nottingham Forest","Sunderland","Tottenham Hotspur"],"laliga":["Deportivo Alavés","Athletic Club","Atlético de Madrid","FC Barcelona","Real Betis","RC Celta","RC Deportivo","Elche CF","RCD Espanyol","Getafe CF","Levante UD","Málaga CF","CA Osasuna","Racing Santander","Rayo Vallecano","Real Madrid","Real Sociedad","Sevilla FC","Valencia CF","Villarreal CF"],"bundesliga":["1. FC Köln","1. FC Union Berlin","1. FSV Mainz 05","Bayer 04 Leverkusen","Borussia Dortmund","Borussia Mönchengladbach","Eintracht Frankfurt","FC Augsburg","FC Bayern München","FC Schalke 04","Hamburger SV","RB Leipzig","SC Paderborn 07","SC Freiburg","SV Elversberg","SV Werder Bremen","TSG Hoffenheim","VfB Stuttgart"],"ligue1":["AJ Auxerre","Angers SCO","AS Monaco","Estac Troyes","FC Lorient","Havre Athletic Club","Le Mans FC","LOSC Lille","OGC Nice","Olympique de Marseille","Olympique Lyonnais","Paris FC","Paris Saint-Germain","RC Lens","RC Strasbourg Alsace","Stade Brestois 29","Stade Rennais FC","Toulouse FC"],"eredivisie":["ADO Den Haag","Ajax","AZ","Excelsior Rotterdam","FC Groningen","FC Twente","FC Utrecht","Feyenoord","Fortuna Sittard","Go Ahead Eagles","N.E.C. Nijmegen","PEC Zwolle","PSV","SC Cambuur","sc Heerenveen","Sparta Rotterdam","Telstar","Willem II"],"primeira":["Académico","Casa Pia AC","CD Nacional","Estoril Praia","Estrela Amadora","FC Alverca","FC Arouca","FC Famalicão","FC Porto","Gil Vicente FC","Marítimo M.","Moreirense FC","Rio Ave FC","Santa Clara","SC Braga","SL Benfica","Sporting CP","Vitória SC"],"seriea":["Atalanta","Bologna","Cagliari","Como","Fiorentina","Frosinone","Genoa","Internazionale","Juventus","Lazio","Lecce","Milan","Monza","Napoli","Parma","Roma","Sassuolo","Torino","Udinese","Venezia"]};
const DEFAULT_STARTS={"Arsenal":90,"Aston Villa":86,"Manchester City":85,"Manchester United":82,"Liverpool":82,"Chelsea":78,"AFC Bournemouth":76,"Crystal Palace":75,"Sunderland":73,"Brighton & Hove Albion":72,"Brentford":71,"Newcastle United":70,"Fulham":69,"Everton":68,"Nottingham Forest":68,"Tottenham Hotspur":66,"Leeds United":65,"Coventry City":62,"Ipswich Town":59,"Hull City":56,"FC Barcelona":89,"Real Madrid":87,"Atlético de Madrid":86,"Villarreal CF":80,"Real Betis":76,"Rayo Vallecano":74,"RC Celta":72,"Getafe CF":70,"Valencia CF":68,"Real Sociedad":68,"RCD Espanyol":66,"Athletic Club":66,"Sevilla FC":65,"Deportivo Alavés":63,"Elche CF":62,"Levante UD":61,"CA Osasuna":61,"Racing Santander":59,"RC Deportivo":57,"Málaga CF":55,"Club Brugge":72,"Royale Union Saint-Gilloise":69,"STVV":63,"RSC Anderlecht":61,"KAA Gent":60,"KRC Genk":59,"KV Mechelen":57,"Standard de Liège":56,"KVC Westerlo":54,"Royal Antwerp FC":54,"Sporting Charleroi":53,"OH Leuven":52,"SV Zulte Waregem":50,"RAAL La Louvière":49,"Cercle Brugge":49,"KV Kortrijk":46,"SK Beveren":45,"Lommel SK":44,"FC Bayern München":88,"Borussia Dortmund":82,"Bayer 04 Leverkusen":82,"Eintracht Frankfurt":78,"VfB Stuttgart":77,"RB Leipzig":77,"SC Freiburg":73,"TSG Hoffenheim":69,"1. FSV Mainz 05":68,"Borussia Mönchengladbach":68,"SV Werder Bremen":65,"1. FC Union Berlin":64,"1. FC Köln":62,"FC Augsburg":61,"Hamburger SV":61,"FC Schalke 04":58,"SC Paderborn 07":55,"SV Elversberg":53,"Paris Saint-Germain":88,"Olympique de Marseille":78,"AS Monaco":77,"LOSC Lille":75,"Olympique Lyonnais":74,"RC Lens":71,"RC Strasbourg Alsace":70,"OGC Nice":69,"Stade Rennais FC":67,"Stade Brestois 29":65,"Toulouse FC":64,"AJ Auxerre":61,"FC Lorient":60,"Paris FC":60,"Havre Athletic Club":58,"Angers SCO":57,"Estac Troyes":55,"Le Mans FC":54,"PSV":80,"Feyenoord":76,"Ajax":73,"AZ":70,"FC Twente":69,"N.E.C. Nijmegen":68,"FC Utrecht":67,"FC Groningen":62,"Go Ahead Eagles":62,"sc Heerenveen":61,"Sparta Rotterdam":60,"Fortuna Sittard":59,"PEC Zwolle":57,"Excelsior Rotterdam":55,"ADO Den Haag":55,"Willem II":54,"SC Cambuur":53,"Telstar":52,"FC Porto":80,"Sporting CP":79,"SL Benfica":79,"SC Braga":72,"Vitória SC":67,"FC Famalicão":64,"Santa Clara":62,"Moreirense FC":61,"Estoril Praia":60,"FC Arouca":59,"Gil Vicente FC":59,"Rio Ave FC":58,"Casa Pia AC":57,"CD Nacional":56,"Estrela Amadora":55,"Marítimo M.":54,"FC Alverca":53,"Académico":52,"Internazionale":85,"Napoli":83,"Juventus":81,"Milan":80,"Roma":79,"Atalanta":78,"Bologna":74,"Lazio":74,"Fiorentina":72,"Como":70,"Sassuolo":66,"Torino":65,"Genoa":64,"Udinese":63,"Parma":62,"Cagliari":61,"Lecce":59,"Monza":58,"Venezia":56,"Frosinone":55};
const DEFAULT_SETTINGS={"k":2.97,"scale":40,"favoriteFactor":0.9,"upsetFactor":1.2,"homeWinFactor":0.9,"homeLossFactor":1.1,"homeDrawGainFactor":0.95,"homeDrawLossFactor":1.05,"awayWinFactor":1.1,"awayLossFactor":0.9,"awayDrawGainFactor":1.05,"awayDrawLossFactor":0.95,"margin1":1,"margin2":1.15,"margin3":1.3,"margin4":1.45,"margin5":1.6,"goodThreshold":0,"goodWinFactor":0,"goodLossFactor":0,"topThreshold":0,"topWinFactor":0,"topLossFactor":0,"eliteThreshold":0,"eliteWinFactor":0,"eliteLossFactor":0,"minRating":30,"maxRating":90,"externalRating":40,"factor_jpl":0.5,"factor_epl":0.8,"factor_laliga":0.75,"factor_bundesliga":0.78,"factor_ligue1":0.7,"factor_eredivisie":0.65,"factor_primeira":0.65,"factor_seriea":0.78,"factor_ucl":1,"factor_uel":0.8,"factor_uecl":0.6};
const COMP={
 jpl:{name:"Jupiler Pro League",short:"JPL",type:"domestic",league:"jpl",country:"Belgium"},
 epl:{name:"Premier League",short:"EPL",type:"domestic",league:"epl",country:"England"},
 ligue1:{name:"Ligue 1",short:"Ligue 1",type:"domestic",league:"ligue1",country:"France"},
 bundesliga:{name:"Bundesliga",short:"Bundesliga",type:"domestic",league:"bundesliga",country:"Germany"},
 seriea:{name:"Serie A",short:"Serie A",type:"domestic",league:"seriea",country:"Italy"},
 eredivisie:{name:"Eredivisie",short:"Eredivisie",type:"domestic",league:"eredivisie",country:"Netherlands"},
 primeira:{name:"Liga Portugal",short:"Portugal",type:"domestic",league:"primeira",country:"Portugal"},
 laliga:{name:"LaLiga",short:"LaLiga",type:"domestic",league:"laliga",country:"Spain"},
 ucl:{name:"Champions League",short:"UCL",type:"europe",country:"UEFA"},
 uel:{name:"Europa League",short:"UEL",type:"europe",country:"UEFA"},
 uecl:{name:"Conference League",short:"UECL",type:"europe",country:"UEFA"}
};
const COMP_ORDER=["jpl","epl","laliga","bundesliga","ligue1","eredivisie","primeira","seriea","ucl","uel","uecl"];
const UEFA_NAV_ORDER=["ucl","uel","uecl"];
const COUNTRY_NAV_ORDER=[["Belgium","jpl"],["England","epl"],["France","ligue1"],["Germany","bundesliga"],["Italy","seriea"],["Netherlands","eredivisie"],["Portugal","primeira"],["Spain","laliga"]];
const ALL_TRACKED=[...new Set(Object.values(TEAMS_BY_LEAGUE).flat())];
const STORAGE_KEY="europeClubCoeff2026_27_v1";
const SCORE_SYNC_WORKFLOW="https://github.com/Hugo28j/Hugo28j.github.io/actions/workflows/sync-football-results.yml";
